version: "3.7"
services:
  clients-database:
    container_name: clients-database
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: clients
